External DB support
linuxserver/docker-papermerge pull request #20
Opened 2021-01-13 12:59 UTC by nmaggioni

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [X] I have read the [contributing](https://github.com/linuxserver/docker-papermerge/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Add the missing dependencies to use external MySQL/PostgreSQL databases.

Potentially closes #9, the defaults configs must be altered on disk after the first run.

## Benefits of this PR and context:

In some deployment contexts using a bind-mounted local SQLite DB isn't feasible (ex.: K8S with underlying NFS shares) and using a separate DB instance is preferable.

2021-01-13 13:08 UTC, tobbenb requested changes
Please don't use -dev packages. As far as I know it's not needed.

2021-01-13 13:53 UTC, nmaggioni commented
@tobbenb Fixed and tested, thanks.

2021-02-07 17:09 UTC, Roxedus commented
Please resolve the conflict.

2021-02-07 18:19 UTC, Roxedus approved these changes

2021-02-07 18:19 UTC, merged